Fix `jinja2` version conflicts
Manually ran `pip-complie` to generate new requirements{_dev}.txt files with the correct version of `jinja2`
This resolves error when running `pip install -r requirements{_dev}.txt`:

```
ERROR: ebay-multilocation-item-notifier 0.0.1 has requirement Jinja2==3.1.4, but you'll have jinja2 3.0.3 which is incompatible.
```